
variables:

  imageAppVersion: "1.0.1"

  # increase this when you need scale up
  replicaCount: 1

  imagePullPolicy: Always

  serviceType: NodePort

  # service port, this provide traffic to ingress within this port
  servicePort: 80

  # target container port
  serviceTargetPort: 3000
  serviceNodePort: 32001

  #app buil image
  imageRepository: "01720588884/ec-service"

