name: prod

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Install yq to parse YAML
      - name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install -y yq

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Build and push ec-service with version from values.yaml
      - name: Build and push ec-service
        run: |
          IMAGE_VERSION=$(yq e '.variables.imageAppVersion' ./ec-service/deploy/values.yaml)
          echo "Building ec-service:$IMAGE_VERSION"
          docker build -t ${{ secrets.DOCKER_USER }}/ec-service:$IMAGE_VERSION -f ec-service/Dockerfile ec-service
          docker push ${{ secrets.DOCKER_USER }}/ec-service:$IMAGE_VERSION

      # Build and push nid-service with version from values.yaml
      - name: Build and push nid-service
        run: |
          IMAGE_VERSION=$(yq e '.variables.imageAppVersion' ./nid-service/deploy/values.yaml)
          echo "Building nid-service:$IMAGE_VERSION"
          docker build -t ${{ secrets.DOCKER_USER }}/nid-service:$IMAGE_VERSION -f nid-service/Dockerfile nid-service
          docker push ${{ secrets.DOCKER_USER }}/nid-service:$IMAGE_VERSION
